
name = "DashCytoscape"
uuid = "1b08a953-4be3-4667-9a23-85cc21bfd5e9"
authors = ["The Plotly Team <cytoscape@plotly.com>"]
version = "1.0.2"

[deps]
Dash = "1b08a953-4be3-4667-9a23-3db579824955"

[compat]
julia = "1.2"
Dash = "0.1.3, 1.0"
